name: Build Wheels

on:
  push:
    branches:
      - main  # Run on pushes to the 'main' branch.

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]  # Platforms to build on.
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install system dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y python3-dev build-essential libssl-dev

      - name: Install dependencies (macOS)
        if: runner.os == 'macOS'
        run: brew install openssl

      - name: Upgrade pip and setuptools
        run: pip install --upgrade pip setuptools wheel

      - name: Install cibuildwheel
        run: pip install cibuildwheel

      - name: Clean up dist directory
        run: rm -rf dist/

      - name: Build Wheels
        env:
          CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-*"  # Specify Python versions
        run: cibuildwheel --output-dir dist

      - name: Upload Wheels
        if: success()  # Run only if the build succeeds
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: dist/
