name: Build Wheels
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CIBW_BUILD: "cp38-* cp39-* cp310-* cp311-* cp312-*"
  CIBW_ARCHS_MACOS: "x86_64 arm64"
  CIBW_ENVIRONMENT_WINDOWS: >-
    OPENSSL_ROOT_DIR='C:/Program Files/OpenSSL-Win64'
    INCLUDE='C:/Program Files/OpenSSL-Win64/include;%INCLUDE%'
    LIB='C:/Program Files/OpenSSL-Win64/lib;%LIB%'
  CIBW_ENVIRONMENT_MACOS: >-
    LDFLAGS='-L/usr/local/opt/openssl@3/lib' 
    CPPFLAGS='-I/usr/local/opt/openssl@3/include'
    OPENSSL_ROOT_DIR='/usr/local/opt/openssl@3'
    OPENSSL_INCLUDE_DIR='/usr/local/opt/openssl@3/include'
    OPENSSL_LIB_DIR='/usr/local/opt/openssl@3/lib'
  CIBW_BUILD_VERBOSITY: 3
  
jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install OpenSSL (macOS)
        if: runner.os == 'macOS'
        run: |
          brew install openssl@3
          brew link openssl@3 --force
          echo "LDFLAGS=-L/usr/local/opt/openssl@3/lib" >> $GITHUB_ENV
          echo "CPPFLAGS=-I/usr/local/opt/openssl@3/include" >> $GITHUB_ENV
          echo "OPENSSL_ROOT_DIR=/usr/local/opt/openssl@3" >> $GITHUB_ENV
          echo "OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl@3/include" >> $GITHUB_ENV
          echo "OPENSSL_LIB_DIR=/usr/local/opt/openssl@3/lib" >> $GITHUB_ENV
          
      - name: Install OpenSSL (Windows)
        if: runner.os == 'Windows'
        run: |
          choco install openssl --force
          echo "OPENSSL_ROOT_DIR=C:/Program Files/OpenSSL-Win64" >> $GITHUB_ENV
          echo "INCLUDE=C:/Program Files/OpenSSL-Win64/include;%INCLUDE%" >> $GITHUB_ENV
          echo "LIB=C:/Program Files/OpenSSL-Win64/lib;%LIB%" >> $GITHUB_ENV
          
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install cibuildwheel==2.16.2
          python -m pip install requests
          
      - name: Build wheels
        run: |
          python -m cibuildwheel --print-build-identifiers
          python -m cibuildwheel --output-dir wheelhouse
        env:
          # For macOS ensure compiler can find OpenSSL
          MACOSX_DEPLOYMENT_TARGET: "10.15"
          
      - name: Upload wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build source distribution
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install build requests
      - name: Build SDist
        run: python -m build --sdist
      - name: Upload SDist
        uses: actions/upload-artifact@v3
        with:
          name: sdist
          path: dist/*.tar.gz

  publish:
    needs: [build_wheels, build_sdist]
    runs-on: macos-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Move wheels to dist directory
        run: |
          mkdir -p dist/all
          find dist -type f -name "*.whl" -exec mv {} dist/all/ \;
          find dist -type f -name "*.tar.gz" -exec mv {} dist/all/ \;
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages-dir: dist/all/